name: CI # Триггер запускает пайплайн при пуше в любую ветку

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.8'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        # Сохраняем отчет в формате JSON
        run: bandit -ll -ii -r . -f json -o bandit-report.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        # Выполнять этот шаг независимо от результата предыдущих
        if: always()
        with:
          # Имя артефакта при экспорте
          name: bandit-findings.json
          path: bandit-report.json

  image_scan:
    # Каждый новый джоб запускается в новой изолированной среде
    name: Build and Run Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      # Исправление проблемы с DNS / сетью внутри Docker-контейнеров
      - name: Fix Docker DNS
        run: |
          echo '{"dns": ["8.8.8.8", "1.1.1.1"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Build Docker Image
        run: docker build -f Dockerfile -t mytestapp:latest .

      - name: Docker Scout Scan
        uses: docker/scout-action@v1.15.1
        with:
          dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          command: quickview,cves
          only-severities: critical,high
          sarif-file: scout-report.sarif
          # По умолчанию exit-code равен true (0). 
          # true здесь заставит пайплайн упасть, если найдены уязвимости.
          exit-code: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: docker-scout-findings
          path: scout-report.sarif

  dast_scan:
    name: Deploy and Run DAST Scan with Nikto
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Repository
        uses: actions/checkout@v6

      - name: Verify Directory Structure
        run: ls -la

      - name: Run Installer Script
        run: bash installer.sh

      - name: Apply Migrations
        run: python3 manage.py migrate

      - name: Run Server
        run: nohup python3 manage.py runserver 0.0.0.0:8000 &

      - name: Wait for Server to Start
        run: sleep 10

      - name: Check Server Availability
        run: curl -I http://127.0.0.1:8000

      - name: Install Nikto
        run: sudo apt-get update && sudo apt-get install -y nikto

      - name: Run Nikto Scan
        # `|| true` гарантирует, что пайплайн не упадет до того, как загрузит отчет, 
        # даже если Nikto найдет кучу уязвимостей.
        run: |
          nikto -h http://127.0.0.1:8000 -o nikto-report.html -Format html || true

      - name: Verify Nikto Report File
        run: ls -la

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: nikto-report
          path: nikto-report.html
