dast_scan:
    name: Deploy and Run DAST Scan with Nikto
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Repository
        uses: actions/checkout@v6

      - name: Verify Directory Structure
        run: ls -la

      - name: Run Installer Script
        run: bash installer.sh

      - name: Apply Migrations
        run: python3 manage.py migrate

      - name: Run Server
        run: nohup python3 manage.py runserver 0.0.0.0:8000 &

      - name: Wait for Server to Start
        run: sleep 10

      - name: Check Server Availability
        run: curl -I http://127.0.0.1:8000

      - name: Install Nikto
        run: sudo apt-get update && sudo apt-get install -y nikto


      - name: Run Nikto Scan
        run: |
          nikto -h http://127.0.0.1:8000 -o nikto-report.html -Format html
      - name: Verify Nikto Report File
        run: ls -la

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: nikto-report
          path: nikto-report.html
